CREATE DATABASE recipe_book

use recipe_book;

CREATE TABLE recipes (
    id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
	recipename VARCHAR(30) NOT NULL,
	ingredients VARCHAR(100) NOT NULL,
	recipe VARCHAR(300) NOT NULL,
    difficulty VARCHAR(30) NOT NULL,
	date TIMESTAMP
);

CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
